### ISSUE TITLE
bas handshake/connection reset error

### ISSUE THREAD

**Issue by dawg6** [observerss/pygodaddy#21]
Hi,

I used to get this once in a while (I run a script every hour and it would happen maybe once every few days), and I had attributed the error it to my ISP or the internet. 

But now I am getting this error every single time. Any thoughts on what might be causing this?

I am running pygodaddy 0.2.2 on Ubuntu 3.19.0-25-generic

```
Traceback (most recent call last):
  File "./godaddy.py", line 14, in <module>
    client.login(GODADDY_USERNAME, GODADDY_PASSWORD)
  File "/usr/local/lib/python2.7/dist-packages/pygodaddy/client.py", line 99, in login
    r = self.session.get(self.default_url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: SysCallError(104, 'ECONNRESET')
```

**Comment by dawg6** [comment]
I got past this issue, then I was getting a different error (connection refushed because too many attempts).

I ended up switching to godaddypy which seems to work well.
